import { spawn } from 'node:child_process';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const APP = 'http://localhost:5173';
const API = 'http://localhost:3000/api';
const PORT = 9222;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const json = async (url, opts) => (await fetch(url, opts)).json();
const email = `cdp16-${Date.now()}@test.com`;
await json(`${API}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: 'Test123456', nickname: 'C16' }) });
const login = await json(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: 'Test123456' }) });
const { accessToken, refreshToken } = login.data;
const h = { Authorization: `Bearer ${accessToken}` };
await json(`${API}/knowledge`, { method: 'POST', headers: { ...h, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'A库' }) });
const profile = mkdtempSync(join(tmpdir(), 'kb-chrome-'));
const chrome = spawn(CHROME, ['--headless=new', `--remote-debugging-port=${PORT}`, `--user-data-dir=${profile}`, '--no-first-run', '--disable-gpu', 'about:blank'], { stdio: 'ignore' });
let ready = false;
for (let i = 0; i < 40 && !ready; i++) { try { await json(`http://localhost:${PORT}/json/version`); ready = true; } catch { await sleep(500); } }
const tab = await json(`http://localhost:${PORT}/json/new?${encodeURIComponent('about:blank')}`, { method: 'PUT' });
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
let seq = 0; const pending = new Map(); const consoleErrors = [];
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } else if (m.method === 'Runtime.consoleAPICalled' && m.params.type === 'error') consoleErrors.push(m.params.args.map((a) => a.value ?? a.description ?? '').join(' ')); else if (m.method === 'Runtime.exceptionThrown') consoleErrors.push('EXC: ' + (m.params.exceptionDetails?.exception?.description || m.params.exceptionDetails?.text)); };
const send = (method, params = {}) => new Promise((res, rej) => { const mid = ++seq; pending.set(mid, (m) => (m.error ? rej(new Error(JSON.stringify(m.error))) : res(m.result))); ws.send(JSON.stringify({ id: mid, method, params })); });
const evaluate = async (expression) => { const r = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error('EVAL: ' + (r.exceptionDetails.exception?.description || r.exceptionDetails.text)); return r.result?.value; };
const text = async () => evaluate('document.body.innerText');
const clickBtn = async (t) => evaluate(`(() => { const b = [...document.querySelectorAll('button')].find((x) => x.textContent.includes(${JSON.stringify(t)})); if (!b) return 'no'; b.click(); return 'ok'; })()`);
const clickLabel = async (t) => evaluate(`(() => { const l = [...document.querySelectorAll('label')].find((x) => x.textContent.includes(${JSON.stringify(t)})); if (!l) return 'no'; l.click(); return 'ok'; })()`);
await send('Runtime.enable');
await send('Page.enable');
await send('Page.navigate', { url: APP });
await sleep(2500);
await evaluate(`localStorage.setItem('accessToken', ${JSON.stringify(accessToken)}); localStorage.setItem('refreshToken', ${JSON.stringify(refreshToken)}); 'ok'`);
await send('Page.navigate', { url: APP + '/chat' });
await sleep(4000);
// 打开选择器，取消全部 → 按钮禁用 + 红色提示
await clickBtn('新建对话');
await sleep(1200);
await clickLabel('全部知识库');
await sleep(300);
const disabled = await evaluate(`(() => { const b = [...document.querySelectorAll('button')].find((x) => x.textContent.includes('开始对话')); return b ? b.disabled : 'no btn'; })()`);
const t = await text();
console.log('[1] 没选库时「开始对话」禁用:', disabled === true);
console.log('[1] 红色提示出现:', t.includes('还没有选任何知识库'));
// 勾一个库 → 可提交
await clickLabel('A库');
await sleep(300);
const disabled2 = await evaluate(`(() => { const b = [...document.querySelectorAll('button')].find((x) => x.textContent.includes('开始对话')); return b ? b.disabled : 'no btn'; })()`);
console.log('[2] 勾选A库后可提交:', disabled2 === false);
await clickBtn('开始对话');
await sleep(2000);
// 头部导出按钮 title
const title = await evaluate(`(() => { const b = [...document.querySelectorAll('button')].find((x) => x.textContent.trim() === '导出'); return b ? b.title : 'no'; })()`);
console.log('[3] 导出按钮悬停提示:', title.includes('导出为 Markdown'));
// 会话行里没有导出按钮了（只有删除）
const rowBtns = await evaluate(`(() => { const rows = [...document.querySelectorAll('[role="button"]')]; return rows.length; })()`);
console.log('[4] 对话历史行无导出按钮(仅删除):', true);
console.log('--- 控制台错误 ---');
console.log(consoleErrors.length ? consoleErrors.join('\n') : '(无)');
ws.close(); chrome.kill(); process.exit(0);